---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Título
        | Subtítulo
        | Subtítulo
author:
- name: Darihana Linares Laureano
  affiliation: "Estudiante de Licenciatura en Geografía mención recursos naturales y ecoturismo, Universidad Autónoma de Santo Domingo (UASD)"
abstract: "Resumen del manuscrito"
keywords: "palabra clave 1, palabra clave 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{
    \setcounter{table}{0}
    \renewcommand{\thetable}{S\arabic{table}}
    \setcounter{figure}{0}
    \renewcommand{\thefigure}{S\arabic{figure}}
    }
---



# Introducción

Desde mediados del siglo XVII es posible visualizar el interés del hombre a estudiar la flora, la fauna y el medio en el que están en conjunto con las interacciones que se producen entre ellos, pero no es hasta mediados del siglo XIX cuando se introduce el término Ecología y su definición, que se empieza a englobar en este tipo de estudios en una categoria [@de2003ecologia]. A partir de este punto se reconocieron distintos campos de estudios y se implementaron nuevos métodos de análisis, entre los cuales destacan la ecología númerica y métodos como el análisis multivariático. Según @legendre2012numerical, la ecología númerica no es más que una de las disciplinas de la ecología cuantitativa, la cual a la vez es una de las divisiones de la ecología matemática. 

La ecología númerica se concentra en el estudio y análisis de conjuntos de datos ecológicos, a fin de poder detallar y comprender la configuración de los conjuntos de datos, combinando diversas perspectivas númericas y disciplinas, procedentes de la Geografía, las matemáticas física, taxonomía númerica, párametros estadísticos y otros más [@legendre2012numerical]. El análisis de conjuntos de datos ecológicos, especialmente de la flora, resulta importante tanto para la ciencia, como para la economía o el sector de salud, por eso se han establecido distintas parcelas permantes de medición y monitoreo forestal donde se colectan datos sobre la diversidad forestal, su estructura, el crecimiento y su productividad [@pineda2014analisis]. En el estudio de las plantas a través de la Ecología Númerica se usan diversas técnicas que permiten obtener información sobre el rango de asociación, agrupamiento, ordenamiento, diversidad, autocorrelación, etcétera, diferentes herramientas para usar las ténicas (ver tabla \ref{tab:tecnicas}).

La medición de la asociación es un coeficiente que sirve para medir y asociar los datos de variables cualitativos y cuantitativos. La medición de estas variables se puede hacer por dos modos el Q y el R, el primero consiste en hacer una comparación de un duo de objetos y el segundo consiste en realizar una descripción de un par de objetos y luego compararlos. Para el modo Q se miden la asociación según la similaridad o disimilaridad de un par de objetos. Mientras que para el modo R se mide el grado de dependecia existente entre las variables, entre los cuales se puede mencionar la covarianza o el coeficiente de correlación [@borcard2011numerical].

En cambio, el análisis de agrupamiento o cluster análisis es una técnica que consiste en separar un conjunto de datos y luego estructurarlos, sin dejar uno fuera de lugar, como subconjuntos con distintas categorias o jerarquias de acuerdo a sus característica. La finalidad de hacer un agrupamiento es identificar los pequeños grupos dispersos en un espacio discreto pero constante, este agrupamiento divide en conjunto de objetos a estudiar, por lo que es necesario e importante que cada objeto agrupado en otros subgrupos no se encuentre en otros [@borcard2011numerical].

En el caso del análisis de ordenaminto, son técnicas que consisten en simplificar la magnitud de los datos. Todas estas técnicas muestran las predisposiciones esenciales de variabilidad de cada dato que se encuentran en un campo de dimensiones simplificadas, organizando los ejes con rangos decreciente de varianza explicada en cada uno de los ejes sucesivo, de forma convencional. Estos tipos de análisis pueden ser tanto no restringido o simple, como restringido o canónico. En donde para el primero, las tendencias o predisposiciones del grupo que interesa no esta restringida por otro grupo. Entre sus técnicas principales de análisis estan los de componentes principales (PCA) basado en un vector propio y se utiliza en datos cuantitativos sin tratamiento preservando la distancia euclídea, los de correspondencia (CA) que se usa en datos frecuentes con dimensiones uniformes y positivos, y los de coordenadas principales (PCoA) que se concentra en organizar las matrices de disimilaridad, usualmente, con el modo Q en vez de tablas de sitio por variables [@borcard2011numerical]. 

Mientras que, para el segundo análisis de ordenamiento, restringido o canónico, a diferencia de la simple, es una técnica que relaciona dos  o más conjunto de datos en el proceso de organización u ordenación. Algunas de sus técnicas principales son análisis de redundancia (RDA) que consiste en la combinación de la regresión y PCA que funciona como una extensión de diversos análisis que muestran la respuesta multivariante de datos, y el análisis de correspondencia canónica (CCA) que funciona como un aproximado de una regresión Gaussiana multivariante, además, este se caracteriza por organizar las especies en todos los ejes canónicos acore a su configuración ecológica óptima [@borcard2011numerical].

En cuanto a la diversidad, según @borcard2011numerical y @magurran1988ecological, esto alude a la variedad y cantidad de especies en un espacio determinado, esta variedad también se produce a nivel de comunidad. La diversidad puede La diversidad va desde la diversidad local, hasta heterogeneidad espacial de esta diversidad. La diversidad de especies considerada como un número unico puede ser medida por la riqueza o la rarificación de especies usando la notación q o por la presencia o ausencia de los datos de esta. Según @whittaker1972evolution, el entendimiento de la diversidad y los cambios que conllevan, asociados a la configuración del relieve los componentes alfa, beta y gamma serian de mucha utilidad. Donde la primera se refiere a la riqueza de las especies existentes en una comunidad determinada, considerada homogénea. La segunda, se trata de el rango de cambios que se producen en la estructura de especies que estan en diferentes comunidades en un espacio. Y la última, se refiere a la riqueza de especies de forma conjuntiva que hay en una comunidad y que integra un espacio determinado.

La autocorrelación, según @borcard2011numerical, forma parte de los análisis espaciales  aplicados a datos ecológicos, que se produce por distintos procesos y que mide puntos cercanos para afirmar si estos poseen valores similares o distintos, por lo que la correlación puede ser una correlación positiva o negativa.

La Myrtaceae son una familia de plantas de árboles y arbustos bastante numerosas compuestas caracterizadas por ser leñosas. Esta familia de plantas pertenece al orden de los Myrtales, teniendo a nivel mundial 129 géneros y aproximadamente 5330 especies [@pereztree]. De sus caracterisiticas físicas se destacan sus hojas simples y opuestas, tienden a ser perennes por lo que resulta poco común ver individuos caducifolios, sus flores son hermafroditas y comunmente son de color blanco con simetría radial, según la especie de esta familia los frutos tienen forma de bayas o cápsulas secas. De esta familia el género más conocido es el Eucalypto Eucalyptus por sus propiedades medicinales y su madera dura. Esta familia esta distribuida en todos los continentes, pero predominan en América, África y Oceanía, en climas templados, tropicales y subtropicales. Muchos consideran que la importancia de esta familia está en lo económico, como la producción de frutas para venta de zumos y mermeladas, producción de madera, producción de papel, de carbón, además de ser usadas en la industria farmacéutica, se usa en la cosmetología y en la producción de especias [@josemyrtaceae; @encymyrtaceae; @sandra2019myrtaceae].

El estudio de la biodiversidad de la flora en especial de una especie vegetal es importante, debido a que permite conocer sus caracteristicas propias, ecosistemicas, su distribución, su capacidad productiva, su potencial de uso y aportes a los humanos como a su ecosistema. Por todo lo anterior, es importante determinar el objetivo de este estudio, el cual se fragmenta asi: a) identificar si los grupos de mi familia, Myrtaceae, se organizan de forma discontinua y acorde a la composición de las especies; b) indagar si existe algun tipo de patrón que sea o no sea consistente con alguna variable ambiental o atributo; c) determinar cuantas especies indicadoras hay o si hay alguna con preferencia por ciertas condiciones ambientales o atributos; d) investigar, en un espacio bidimensional, si hay una tendencia de ordenanción visible de las especies de Myrtaceae; e) conocer si las tendencias de ordenación se asocian con las variables ambientales o atributos; f) determinar, de acuerdo a la estimación de riqueza, si mi familia esta bien representada, tomando como buena representación un 85%; g) investigar si existe una alguna asociación entre la diversidad alpha y las variables ambientales o atributos y cuales son estas; h) conocer si hay algún tipo de contribución local o de alguna especie a la diversida beta; i) identificar si hay alguna especie que presente algún patrón aglomerado, cuál es y si presenta alguna asociación con las variables ambientales; j) y determinar si los modelos de distribución de especies (SDM) predicen adecuadamente las ocurrencias de las especies. 
 
# Área de estudio

BCI (Isla de Barrio Colorado) es una isla que pertenece a Panamá,  que se formó cuando las aguas del río Chagres fueron represadas para construir el Canal de Panamá [@perez2005metodologia]

con una parcela permanente de medición y monitoreo forestal con 


# Metodología

\ldots

# Resultados
Ver tabla \ref{tab:abun_sp} y figura \ref{fig:abun_sp_q}



# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias
